[package]
name = "quick-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["quickjs-sys"]

[[bin]]
name = "test"
path = "src/lib.rs"

[features]
default = ["async"]
async = ["compio", "flume", "futures-util", "parking_lot"]
json = ["serde", "serde_json"]
mimalloc = ["quickjs-sys/mimalloc"]

[dependencies]
quickjs-sys = { path = "quickjs-sys" }
thiserror = { version = "1", default-features = false }
anyhow = { version = "1", features = ["std"], default-features = false }
log = { version = "0.4", default-features = false }
serde = { version = "1", features = [
    "derive",
], default-features = false, optional = true }
serde_json = { version = "1", features = [
    "std",
], default-features = false, optional = true }
compio = { version = "0.11", features = [
    "runtime",
    "io-uring",
    "time",
], default-features = false, optional = true }
flume = { version = "0.11", features = [
    "async",
], default-features = false, optional = true }
parking_lot = { version = "0.12", default-features = false, optional = true }
futures-util = { version = "0.3", features = [
    "async-await-macro",
], default-features = false, optional = true }
