[package]
name = "quick-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["quickjs-sys"]

[[bin]]
name = "test"
path = "src/lib.rs"

[features]
default = []
mimalloc = ["dep:libmimalloc-sys"]

[dependencies]
quickjs-sys = { path = "quickjs-sys" }
libmimalloc-sys = { version = "0.1", features = [
    "extended",
], default-features = false, optional = true }
thiserror = { version = "2", default-features = false }
log = { version = "0.4", default-features = false }
