[package]
name = "quick-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["quickjs-sys"]

[[bin]]
name = "test"
path = "src/lib.rs"

[features]
default = []
mimalloc = ["dep:libmimalloc-sys"]

[dependencies]
quickjs-sys = { path = "quickjs-sys" }
libmimalloc-sys = { version = "0.1", features = [
    "extended",
], default-features = false, optional = true }
tracing = { version = "0.1", default-features = false }
anyhow = { version = "1", features = ["std"], default-features = false }
thiserror = { version = "2", default-features = false }
flume = { version = "0.11", features = ["async"], default-features = false }
futures-util = { version = "0.3", features = [
    "std",
    "async-await-macro",
], default-features = false }
tokio = { version = "1", features = [
    "macros",
    "rt",
    "sync",
    "time",
], default-features = false }
parking_lot = { version = "0.12", default-features = false }
